# 参考：https://docs.docker.com/compose/compose-file/
version: '3.8'

services:
  webstack_server:
    # restart: alwavs
    build: # 构建自定义镜像
      context: . # 指定 Dockerfile 文件的所在路径
      dockerfile: Dockerfile # 指定 Dockerfile 文件名称
    image: webstack:1.0.1 # 自定义镜像名称及版本，就是上面 build 后的镜像
    container_name: webstack_server
    network_mode: bridge
    ports:
      - 3008:3008
    volumes: # 使用标示的方式必须指定 volumes，这与直接 docker run 不同
      - webstack_server:/nestwebstack
  webstack_admin:
    image: webstack:1.0.1
    container_name: webstack_admin
    network_mode: bridge
    ports:
      - 3009:3009
    volumes: # 当然也可以直接使用绝对路径
      - webstack_admin:/nestwebstack
    command: start:prod_admin

# volume 可为空，为空使用 docker 引擎配置的默认驱动程序
# 也可以自定义存储到其他机器上，可以指定 volume name，不指定默认会加上 stack name 前缀
# https://docs.docker.com/compose/compose-file/#volume-configuration-reference
volumes:
  webstack_admin:
    name: webstack_admin
  webstack_server:
