// 使用阿里的图标，下载阿里图标压缩包，将 iconfot.json 内容复制到 data 即可

// index.html 引入样式
//at.alicdn.com/t/font_1949907_usyu3f16zc.css

const data = {
  id: '1949907',
  name: '彩标',
  font_family: 'iconfont',
  css_prefix_text: 'icon-',
  description: '',
  glyphs: [
    {
      icon_id: '3886597',
      name: '智能云',
      font_class: 'zhinengyun1',
      unicode: 'e607',
      unicode_decimal: 58887,
    },
    {
      icon_id: '3904602',
      name: '智能云＊',
      font_class: 'zhinengyun2',
      unicode: 'e6a5',
      unicode_decimal: 59045,
    },
    {
      icon_id: '5520824',
      name: 'shc 云盾混合云',
      font_class: 'shc',
      unicode: 'e893',
      unicode_decimal: 59539,
    },
    {
      icon_id: '5583169',
      name: 'clouddesktop 云桌面',
      font_class: 'clouddesktopyunzhuomian',
      unicode: 'e89f',
      unicode_decimal: 59551,
    },
    {
      icon_id: '11535046',
      name: '云盘上传',
      font_class: 'yunpanshangchuan',
      unicode: 'e655',
      unicode_decimal: 58965,
    },
    {
      icon_id: '13533440',
      name: 'shc 云盾混合云',
      font_class: 'shcyundunhunheyun',
      unicode: 'e644',
      unicode_decimal: 58948,
    },
    {
      icon_id: '13592923',
      name: 'clouddesktop 云桌面',
      font_class: 'clouddesktopyunzhuomian1',
      unicode: 'e714',
      unicode_decimal: 59156,
    },
    {
      icon_id: '3862637',
      name: '云端',
      font_class: 'yunduan',
      unicode: 'e60f',
      unicode_decimal: 58895,
    },
    {
      icon_id: '7057412',
      name: '服务器监控',
      font_class: 'icon-fuwuqijiankong',
      unicode: 'e681',
      unicode_decimal: 59009,
    },
    {
      icon_id: '13478787',
      name: '云盘',
      font_class: 'A',
      unicode: 'e6f6',
      unicode_decimal: 59126,
    },
    {
      icon_id: '1190673',
      name: 'biotech',
      font_class: 'biotech',
      unicode: 'e60a',
      unicode_decimal: 58890,
    },
    {
      icon_id: '1190674',
      name: 'biohazard',
      font_class: 'biohazard',
      unicode: 'e60b',
      unicode_decimal: 58891,
    },
    {
      icon_id: '1190685',
      name: 'calculator',
      font_class: 'calculator',
      unicode: 'e610',
      unicode_decimal: 58896,
    },
    {
      icon_id: '1190693',
      name: 'cancel',
      font_class: 'cancel',
      unicode: 'e613',
      unicode_decimal: 58899,
    },
    {
      icon_id: '1190705',
      name: 'close_up_mode',
      font_class: 'close_up_mode',
      unicode: 'e618',
      unicode_decimal: 58904,
    },
    {
      icon_id: '1190777',
      name: 'fine_print',
      font_class: 'fine_print',
      unicode: 'e637',
      unicode_decimal: 58935,
    },
    {
      icon_id: '1190782',
      name: 'folder',
      font_class: 'folder',
      unicode: 'e63a',
      unicode_decimal: 58938,
    },
    {
      icon_id: '1190799',
      name: 'idea',
      font_class: 'idea',
      unicode: 'e641',
      unicode_decimal: 58945,
    },
    {
      icon_id: '1190812',
      name: 'landscape',
      font_class: 'landscape',
      unicode: 'e648',
      unicode_decimal: 58952,
    },
    {
      icon_id: '1190823',
      name: 'like',
      font_class: 'like',
      unicode: 'e64d',
      unicode_decimal: 58957,
    },
    {
      icon_id: '1190915',
      name: 'settings',
      font_class: 'settings',
      unicode: 'e679',
      unicode_decimal: 59001,
    },
    {
      icon_id: '1337291',
      name: 'travel',
      font_class: 'Suitcase',
      unicode: 'e601',
      unicode_decimal: 58881,
    },
    {
      icon_id: '1337297',
      name: 'Timezone',
      font_class: 'Timezone',
      unicode: 'e604',
      unicode_decimal: 58884,
    },
    {
      icon_id: '1337308',
      name: 'Train Ticket',
      font_class: 'TrainTicket',
      unicode: 'e60c',
      unicode_decimal: 58892,
    },
    {
      icon_id: '1337318',
      name: 'Wind Rose',
      font_class: 'WindRose',
      unicode: 'e611',
      unicode_decimal: 58897,
    },
    {
      icon_id: '1337320',
      name: 'Waypoint Map',
      font_class: 'WaypointMap',
      unicode: 'e612',
      unicode_decimal: 58898,
    },
    {
      icon_id: '1337321',
      name: 'Worldwide Location',
      font_class: 'WorldwideLocation',
      unicode: 'e614',
      unicode_decimal: 58900,
    },
    {
      icon_id: '1337329',
      name: 'Arena',
      font_class: 'Arena',
      unicode: 'e617',
      unicode_decimal: 58903,
    },
    {
      icon_id: '1337359',
      name: 'Compass',
      font_class: 'Compass',
      unicode: 'e627',
      unicode_decimal: 58919,
    },
    {
      icon_id: '1337380',
      name: 'Globe',
      font_class: 'Globe',
      unicode: 'e632',
      unicode_decimal: 58930,
    },
    {
      icon_id: '1337401',
      name: 'North Direction',
      font_class: 'NorthDirection',
      unicode: 'e63c',
      unicode_decimal: 58940,
    },
    {
      icon_id: '3881868',
      name: '资料,文本',
      font_class: 'ziliao',
      unicode: 'e764',
      unicode_decimal: 59236,
    },
    {
      icon_id: '3904603',
      name: '智能云',
      font_class: 'zhinengyun',
      unicode: 'e6a4',
      unicode_decimal: 59044,
    },
    {
      icon_id: '4520176',
      name: '搜索',
      font_class: 'sousuo',
      unicode: 'e68f',
      unicode_decimal: 59023,
    },
    {
      icon_id: '5233424',
      name: '智能云',
      font_class: 'tubiao-',
      unicode: 'e615',
      unicode_decimal: 58901,
    },
    {
      icon_id: '5618160',
      name: '原型设计',
      font_class: 'yuanxingsheji',
      unicode: 'e61e',
      unicode_decimal: 58910,
    },
    {
      icon_id: '8648200',
      name: '搜索',
      font_class: 'sousuo1',
      unicode: 'e60d',
      unicode_decimal: 58893,
    },
    {
      icon_id: '10480260',
      name: '词云图',
      font_class: 'ciyuntu',
      unicode: 'e927',
      unicode_decimal: 59687,
    },
  ],
}

const iconList: any = []

data.glyphs.forEach((e) => {
  iconList.push({ label: e.name, value: `${data.font_family} ${data.css_prefix_text}${e.font_class}` })
})

export default iconList
