# https://github.com/marketplace/actions/ssh-remote-commands
# https://docs.github.com/cn/actions
name: WebStack CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh WebStack CI
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/nest-webstack
            git pull
            cd server
            docker-compose up --build
            cd ../admin
            npm install
            npm run build
            mkdir -p /home/web/website && cp -rf dist/* /home/web/website
